<section>
    <header class='page-header'>
        <div class='clearfix'>
            <span class='left'><h3> Carrinho </h3></span>
        </div>
    </header>

    <article>
        <table class='table table-bordered table-striped'>
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Quantidade</th>
                    <th>Nome</th>
                    <th>Valor Unitario</th>
                    <th>Total</th>
                    <th>Remover</th>
                    
                </tr>
            </thead>
            <tbody>
                
                	
                	
                	<?php
                		foreach ($cart as $key => $value) {
                			$product= Product::findById($key);
                	?>
                		<tr>
							<td><?= $key; ?></td>
							<td><?= $value ?></td>
							<td><?= $product->getName() ?></td>
							<td><?= $product->getPrice() ?></td> 
							<td><?= $product->getPrice() * $value ?></td>
							<td><input type="checkbox" name="remove[]" value="{$key}"></td>
						</tr>
							
					<?php		
                		}
                	
                	?>
                	
                	
                </tr>
            </tbody>
        </table>
    </article>
</section>