<section>
    <header class='page-header'>
        <div class='clearfix'>
            <span class='left'><h3> Todos os Pedido</h3></span>
        </div>
    </header>

    <article>
        <table class='table table-bordered table-striped'>
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Data</th>
                    <th>Cliente</th>
                    <th>Total</th>
                    <td>Status</td>
                </tr>
            </thead>
            <tbody>
                <?php foreach($orders as $order) {?>
                <tr>
                    <td><?= $order->getId(); ?></td>
                    <td><?= $order->getCreatedAt(); ?></td>
                    
                    
                    <td><?=$order->getUser_Id();?></td>
                    <td><?= $order->getTotal(); ?></td>
                    <td><?= $order->getStatus(); ?></td>
                    <td class='options'>
                        <ul>
                            <li><?= link_to("/admin/pedidos/visualizar/{$order->getId()}",'Visualizar')?></li>
                            <li><?= link_to("/admin/pedidos/remover/{$order->getId()}",'Remover', 'data-confirm="Tem certeza?"')?></li>
                        </ul>
                    </td>
                </tr>
                <?php } ?>
            </tbody>
        </table>
    </article>
    <article>
        <div class="pagination">
			<?php
				$numPages = ceil($numRows / QNT_PROD);
				for ($i = 1; $i <= $numPages; $i++) { echo button_to("/admin/pedidos/?pagina=$i", $i, "page-style"); }
			
			?>
		</div> 
	</article>
</section>