<section>
  	<header class="page-header">
    	<h1>Produtos em destaque</h1>
    	<small class='help-block'> Seja bem-vindo a Loja Virtual </small>
  	</header>

  	<article>
		<div class="container-fluid">
        	<div class="row-fluid">
            <?php $i = 0; foreach($products as $product) {
                if (($i % 3) == 0) {?>
                <ul class="thumbnails">
                    <?php } ?>
                    <li class="span4">
                        <div id="list" class="thumbnail">
                            <?=  link_to("/categoria/{$product->getDepartment_Id()}/produto/{$product->getId()}", image_tag('products', 'list', $product->getPhotoName(), $product->getName())) ?>
                            <h5><?= link_to("/categoria/{$product->getDepartment_Id()}/produto/{$product->getId()}",$product->getName()); ?></h5>
                            <h6><?= $product->getPrice(); ?></h6>
                            <?= button_to("/carrinho/{$product->getId()}", 'Add ao carrinho', 'btn btn-primary btn-small')?>
                            <?= button_to("/fechar/{$product->getId()}", 'Fechar a compra', 'btn btn-small')?>  
                        </div>
                    </li>
                    <?php $i++;
                    if (($i % 3) == 0) { ?>
                </ul>
                <?php } } ?>
        	</div>
    	</div>
	</article>
</section>