<!DOCTYPE HTML>
<html lang="en-US">
<head>
    <meta charset="UTF-8">
    <title><?= APP_NAME ?></title>
    <?php stylesheet_include_tag('bootstrap.min.css', 'bootstrap-responsive.min.css','font-awesome.min.css','bootswatch.css', 'jquery.lightbox.css','jquery.jqzoom.css', 'application.css'); ?>
    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
 </head>
<body>
    <!-- Navbar
    ================================================== -->
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand" href="<?= url_for('/') ?>">LOJA</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li><a id="swatch-link" href="<?= url_for('/') ?>">Home</a></li>
              <li><?= link_to('/produtos','Produtos'); ?></li>
              <?php if (!(current_user())) { ?>
                <li><?= link_to('/login','Login'); ?></li>
                <li><?= link_to('/registre-se','Registre-se'); ?></li>
                <li><?= link_to('/fale-conosco','Fale Conosco'); ?></li>
                <li><?= link_to('/sobre-a-empresa','Sobre a Empresa'); ?></li>
              <?php } else { ?>
                <li><?= link_to('/logout', 'Logout'); ?></li>
                <li><?= link_to('/admin/departamentos','Departamentos'); ?></li>
                <li><?= link_to('/admin/mensagens','Mensagens'); ?></li>
                <li><?= link_to('/admin/produtos','Produtos'); ?></li>
              <?php } ?>
            </ul>
          </div>
        </div>
      </div>
    </div>


  <!-- Subhead ================================================== -->
  <header class="subhead">
    <div class="container">
      <h2>Loja Virtual</h2>
      <p class="lead">Simples, Prática e Funcional</p>
    </div>
    <div class="show-cart">
      <img src="/loja/app/assets/img/cart.png" alt="carrinho de compras" class="size-cart">
      <a href="/loja/carrinho" class="show-items"><?php echo Cart::getItemsOnCart(); ?></a>
    </div>
    <div class="show-search">
      <form id='files-search-form' class='form-search' action='#' method='GET'>
        <div class='input-append'>
          <input type='text' name='search' id='search' class='span9 search-query'>
          <button type='submit' class='btn btn-primary'>Buscar</button>
        </div> 
      </form>
    </div>
  </header>

  <div class="container-fluid">
    <!-- Docs nav ================================================== -->
    <div class="row-fluid">
      <div class="span3">
        <div class="sidebar-nav">
          <ul class="nav nav-tabs nav-stacked nav-fixed">
            <?php 
              if ((!current_user()) || (!current_user()->getAdmin())) { 
                $departments = Department::getAll();
				        foreach($departments as $department) {
          	?>
            	<li><?= link_to("/categoria/{$department->getId()}", "<i class=\"icon-chevron-right\"></i> {$department->getName()}") ?></li>
            <?php }} ?>
          </ul>
          <ul class="nav nav-tabs nav-stacked nav-fixed">
            <?php if (current_user()) { ?>
              <?php if (current_user()->getAdmin()) { ?>
                <li><a><i ></i> Menu Administrativo</a></li>
                <li><?= link_to('/admin/mensagens', '<i class="icon-chevron-right"></i> Mensagens'); ?></li>
                <li><?= link_to('/admin/usuarios', '<i class="icon-chevron-right"></i> Usuários'); ?></li>
            <?php }} ?>
          </ul>

        </div>
      </div>
      <div class="span9">
        <?php foreach(flash() as $key => $value){ ?>
          <div class='alert alert-<?= $key ?>'>
            <a class='close' data-dismiss='alert'>x</a>
            <?= $value ?>
          </div>
        <?php } ?>