 <section>
 	<header class='page-header'>
 		<div class='clearfix'>
 			<h1 class='left'>Formulário de Cadastro de Produtos</h1>
 			<div class='right'>
 				<?= link_to('/admin/produtos', 'Todos os produtos')?>
 			</div>
 		</div>
 	</header>
 	<article>
 		<?php
 			$action = url_for("/admin/produtos");
 			$submit = 'Cadastrar Produto';
 			require 'form.inc.phtml';
 		?>
 	</article>
 </section>