<!DOCTYPE HTML>
<html lang="en-US">
<head>
    <meta charset="UTF-8">
    <title><?= APP_NAME ?></title>
    <?php stylesheet_include_tag('bootstrap.min.css', 'bootstrap-responsive.min.css','font-awesome.min.css','bootswatch.css', 'jquery.lightbox.css','jquery.jqzoom.css', 'application.css'); ?>
    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
 </head>
<body>
    <!-- Navbar
    ================================================== -->
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand" href="<?= url_for('/') ?>">LOJA</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li><a id="swatch-link" href="<?= url_for('/admin') ?>">Home</a></li>
                <?php if (current_user()) { if (current_user()->getAdmin()) { ?>
                  <li><?= link_to('/logout','Sair'); ?></li>
                <?php }} else { ?>
                  <li><?= link_to('/login','Entrar'); ?></li>
                <?php } ?>
                <li><?= link_to('/admin/departamentos','Departamentos'); ?></li>
                <li><?= link_to('/admin/produtos','Produtos'); ?></li>
                <li><?= link_to('/admin/pedidos','Pedidos'); ?></li>
                <li><?= link_to('/admin/mensagens','Mensagens'); ?></li>
            </ul>
          </div>
        </div>
      </div>
    </div>


  <!-- Subhead ================================================== -->
  <header class="subhead">
    <div class="container">
      <h2>Loja Virtual</h2>
      <p class="lead">Simples, Prática e Funcional</p>
    </div>
    <div class="show-cart">
      <img src="/loja/app/assets/img/cart.png" alt="carrinho de compras" class="size-cart">
      <a href="/loja/carrinho" class="show-items"><?php echo Cart::getItemsOnCart(); ?></a>
    </div>
  </header>

  <div class="container-fluid">
    <!-- Docs nav ================================================== -->
    <div class="row-fluid">
      <div class="span3">
        <div class="sidebar-nav">
          <ul class="nav nav-tabs nav-stacked nav-fixed">
          </ul>
          <ul class="nav nav-tabs nav-stacked nav-fixed">
            <li><a><i ></i> Menu Administrativo</a></li>
            <li><?= link_to('/admin/mensagens', '<i class="icon-chevron-right"></i> Mensagens'); ?></li>
            <li><?= link_to('/admin/usuarios', '<i class="icon-chevron-right"></i> Usuários'); ?></li>
          </ul>

        </div>
      </div>
      <div class="span9">
        <?php foreach(flash() as $key => $value){ ?>
          <div class='alert alert-<?= $key ?>'>
            <a class='close' data-dismiss='alert'>x</a>
            <?= $value ?>
          </div>
        <?php } ?>