<section>
	<header class="page-header">
		<h1>Sobre a Empresa</h1>
	</header>

	<article>
		<div class='alert alert-info'>
            <a class='close' data-dismiss='alert'>x</a>
            * Todo contéudo neste não é real, faz parte de um projeto da disciplina de Programação Web 2, sem fins lucrativos para a UTFPR.
        </div>

		<p>	<strong> Loja Virtual de Orgãos </strong></p>

		<p> Cansado de ter que acessar a Deep Web para comprar aquele orgão que parou de funcionar, ou que te encomendaram? Seus problemas acabaram com a chegada da Loja Virtual! </p>

		<p> Só aqui você encontra os melhores orgão, que vão desde os de melhor qualidade ao mais ferrado já visto. </p>

		<p> Levamos até a sua casa, o prazo de entrega pode ser um pouco longo, pois a entrega é feita de bike, mas garantimos 100% da qualidade do orgão durante este processo </p>

		<p><strong> Nosso Endereço: </strong> Rua das Pitangueiras, 31422 </p>
		<p><strong> Cidade: </strong> Casterly Rock </p>
		<p><strong> Estado: </strong> Campina </p>
		<p><strong> País: </strong> Westeros </p>
		<p><strong> Nosso E-mail: </strong> lojavirtual@store.com </p>
	</article>
</section>