<section>
	<header class="page-header">
		<h1>Lista de Produtos</h1>
	</header>
	<article>
		<div class="container-fluid">
        	<div class="row-fluid">
            <?php $i = 0; ?>
            <?php foreach($products as $product) {
                if (($i % 3) == 0) {?>
                <ul class="thumbnails">
                    <?php } ?>
                    <li class="span4">
                        <div id="list" class="thumbnail">
                            <?=  link_to("{$product->getDepartment_Id()}/produto/{$product->getId()}", image_tag('products', 'list', $product->getPhotoName(), $product->getName())) ?>
                            <h5><?= link_to("{$product->getDepartment_Id()}/produto/{$product->getId()}",$product->getName()); ?></h5>
                            <h6><?= $product->getPrice(); ?></h6>
                            <?= button_to("/carrinho/{$product->getId()}", 'Add ao carrinho', 'btn btn-primary btn-small')?>
                            <?= button_to("/carrinho/{$product->getId()}/fechar", 'Fechar a compra', 'btn btn-small')?>                         
                        </div>
                    </li>
                    <?php $i++;
                    if (($i % 3) == 0) { ?>
                </ul>
                <?php } } ?>
        	</div>
    	</div>
	</article>
	<article>
        <div class="pagination">
			<?php
				$numPages = @$numRows % QNT_PROD;
				for ($i = 1; $i <= $numPages; $i++) { echo button_to("?pagina=$i", $i, "page-style"); }
			?>
		</div> 
	</article>
</section>