<section>

	<header class="page-header">
		<h1>Lista de Produtos</h1>
	</header>
	
	<article>
		<div class="row" id="items">
			<?php
			$i=1;
			foreach ($products as $product) {
			if ($i % 5 == 0) {?>
			<div class="row" id="items">
			<?php } ?>
			<div class="span3">
			<div class="thumb">   <?=  image_tag('products', 'thumb', $product -> getPhotoName(), $product -> getName()) ?></div>
			</div>
			<?php
			if ($i % 4 == 0) {?>
		</div>
		<?php }
		
			$i++;
			}
		?>
		
		
	
	</article>
	<article>
		<div class="paginacao">
			<?php
				$numPages=$numRows % QNT_PROD;
				for ($i = 1; $i <= $numPages; $i++) {
					echo link_to("?pagina=$i", $i);
				}
			?>
		</div>
	</article>
</section>
